default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: beehiiv

development:
  <<: *default
  database: challenge_development
  password: password

test:
  <<: *default
  database: challenge_test
  password: password

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
